In [1]:
import json
import csv
 
 
# Opening JSON file and loading the data
# into the variable data
with open('CAT - Peoria v2.json') as json_file:
    data = json.load(json_file)

In [3]:
employee_data = data['features']
 
# now we will open a file for writing
data_file = open('data_file.csv', 'w')

In [4]:
csv_writer = csv.writer(data_file)
 
# Counter variable used for writing
# headers to the CSV file
count = 0
 
for emp in employee_data:
    if count == 0:
 
        # Writing headers of CSV file
        header = emp.keys()
        csv_writer.writerow(header)
        count += 1
 
    # Writing data of CSV file
    csv_writer.writerow(emp.values())
 
data_file.close()

In [5]:
csv_writer

In [6]:
import csv
import pandas as pd

In [8]:
json_csv = pd.read_csv("data_file.csv")
json_csv

,type,properties,geometry
0,Feature,"{'category': 'Site', 'id': 'CATEP', 'name': 'C...","{'type': 'Polygon', 'coordinates': [[[-89.5931..."
1,Feature,"{'category': 'POI', 'id': 'BLCV', 'name': 'Bui...","{'type': 'Polygon', 'coordinates': [[[-89.5899..."
2,Feature,"{'category': 'Floor', 'id': 'BLCV_FL01', 'name...","{'type': 'Polygon', 'coordinates': [[[-89.5899..."
3,Feature,"{'category': 'Room', 'id': 'BLCV_RM01', 'name'...","{'type': 'Polygon', 'coordinates': [[[-89.5911..."
4,Feature,"{'category': 'Room', 'id': 'BLCV_RM02', 'name'...","{'type': 'Polygon', 'coordinates': [[[-89.5913..."
...,...,...,...
632,Feature,"{'category': 'Furniture', 'id': 'BLCV_FR02', '...","{'type': 'Polygon', 'coordinates': [[[-89.5914..."
633,Feature,"{'category': 'Furniture', 'id': 'BLCV_FR03', '...","{'type': 'Polygon', 'coordinates': [[[-89.5913..."
634,Feature,"{'category': 'Furniture', 'id': 'BLCV_FR04', '...","{'type': 'Polygon', 'coordinates': [[[-89.5913..."
635,Feature,"{'category': 'Furniture', 'id': 'BLCV_FR05', '...","{'type': 'Polygon', 'coordinates': [[[-89.5914..."
636,Feature,"{'category': 'Furniture', 'id': 'BLCV_FR06', '...","{'type': 'Polygon', 'coordinates': [[[-89.5914..."

In [12]:
import pandas as pd
df = pd.read_json ('CAT - Peoria v2.json')
export_csv = df.to_csv ('new.csv', index = True, header=True)

In [13]:
json_csv1 = pd.read_csv("new.csv")
json_csv1

,Unnamed: 0,type,features
0,0,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."
1,1,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."
2,2,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."
3,3,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."
4,4,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."
...,...,...,...
632,632,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."
633,633,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."
634,634,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."
635,635,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."
636,636,FeatureCollection,"{'type': 'Feature', 'properties': {'category':..."